modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/oierbravo/create-sifter/issues"
license="MIT"

[[mods]]

modId = "createsifter"
version = "${file.jarVersion}"
updateJSONURL = "https://api.modrinth.com/updates/create-sifting/forge_updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/create-sifting"
displayName = "Create Sifter"
logoFile="logo.png"
description = '''
Gather resources sifting
'''

[[dependencies.createsifter]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId = "create"
    mandatory = true
    versionRange="[0.5.1.e,)"
    ordering = "AFTER"
    side = "BOTH"