modLoader = "javafml"
loaderVersion = "[40,)"
license = "MIT License"
[[mods]]
modId = "createsifter"
version = "${file.jarVersion}"
displayName = "Create Sifter"
logoFile="logo.png"
description = '''
Gather resources sifting
'''

[[dependencies.createsifter]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.createsifter]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,1.19)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.createsifter]]
    modId = "create"
    mandatory = true
    versionRange="[0.5.0.g,)"
    ordering = "AFTER"
    side = "BOTH"

