modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/oierbravo/create-sifter/issues"
license="MIT"

[[mods]]

modId = "createsifter"
version = "${file.jarVersion}"
displayName = "Create Sifter"
logoFile="logo.png"
description = '''
Gather resources sifting
'''

[[dependencies.createsifter]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId = "create"
    mandatory = true
    versionRange="[0.5.0.g,)"
    ordering = "AFTER"
    side = "BOTH"

