modLoader="javafml"
loaderVersion="[43,)"
issueTrackerURL="https://github.com/oierbravo/create-sifter/issues"
license="MIT"

[[mods]]

modId = "createsifter"
version = "${file.jarVersion}"
updateJSONURL = "https://api.modrinth.com/updates/create-sifting/forge_updates.json"
displayName = "Create Sifter"
logoFile="logo.png"
description = '''
Gather resources sifting
'''

[[dependencies.createsifter]]
    modId="forge"
    mandatory=true
    versionRange="[43.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.createsifter]]
    modId = "create"
    mandatory = true
    versionRange="[0.5.1.c,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.createsifter]]
    modId = "kubejs"
    mandatory = false
    versionRange = "[1902.6.1-build.348,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.createsifter]]
    modId = "kubejs_create"
    mandatory = false
    versionRange = "[1902.2.4-build.27,)"
    ordering = "AFTER"
    side = "BOTH"